---
# delete_ami.yml
# This file contains cleanup tasks for the Packer build process

- name: Check if ami already deleted
  ansible.builtin.set_fact:
    skip_delete: true
  when: delete_done | bool

- name: Display delete skip message
  ansible.builtin.debug:
    msg: "AMI's already delete or not exists. skipping..."
  when: skip_delete | default(false)

- name: Mark delete ami as in-progress
  ansible.builtin.set_fact:
    delete_done: true
  when: not delete_done | bool

- name: get the stored AMI ID locally
  ansible.builtin.shell: cat {{ ami_output_dir }}/backend_ami.txt
  register: ami_id
  changed_when: false

- name: Deregister AMI and delete snapshots
  vars:
    component: backend
    AMI_ID: "{{ ami_id.stdout | default('') | trim }}"
    AWS_REGION: "{{ aws_region }}"
    # ami_output_dir: "{{ ami_output_dir }}"
  block:
    - name: Print AMI deregistration message
      ansible.builtin.debug:
        msg: "ðŸš€ Deregistering {{ component | capitalize }} AMI: {{ AMI_ID }}"

    - name: Get snapshot IDs for this AMI
      ansible.builtin.shell: >
        aws ec2 describe-images
        --image-ids {{ AMI_ID }}
        --owner self
        --region {{ AWS_REGION }}
        --query "Images[0].BlockDeviceMappings[].Ebs.SnapshotId"
        --output text
      register: snapshot_ids
      changed_when: false

    - name: Show found snapshot IDs
      when: snapshot_ids.stdout | trim != "None"
      ansible.builtin.debug:
        msg: "ðŸ” Snapshots: {{ snapshot_ids.stdout | trim  }}"

    - name: Deregister the AMI
      shell: >
        aws ec2 deregister-image
        --image-id {{ AMI_ID }}
        --region {{ AWS_REGION }}
      register: dereg_result
      when: snapshot_ids.stdout | trim != "None"
      changed_when: true

    - name: Delete each snapshot
      shell: >
        aws ec2 delete-snapshot
        --snapshot-id {{ snapshot_ids.stdout | trim }}
        --region {{ AWS_REGION }}
      # when: item | trim != ""
      # loop: "{{ snapshot_ids.stdout.split() }}"
      register: delete_snapshot_results
      when: snapshot_ids.stdout | trim != "None"
      changed_when: true

    - name: Show snapshot deletion results
      ansible.builtin.debug:
        msg: "Snapshot deletion result: {{ delete_snapshot_results.stdout_lines }}"
      when: snapshot_ids.stdout | trim != "None"

- name: Delete a backend ami file
  ansible.builtin.file:
    path: "{{ ami_output_dir }}/backend_ami.txt"
    state: absent
