---
- name: Setup Backend Application Server
  hosts: all
  become: yes
  vars:
    app_user: ec2-user
    app_dir: /home/ec2-user/backend
    log_dir: /home/ec2-user/backend/logs
    node_version: "18.x"

  tasks:
    - name: Display bucket name
      debug:
        msg: "Bucket name: {{ bucket_name }}"

    - name: Update system packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Copy application code from S3
      become_user: "{{ app_user }}"
      command: >
        aws s3 cp s3://{{ bucket_name }}/lirw-three-tier/backend {{ app_dir }} --recursive
      args:
        creates: "{{ app_dir }}"

    - name: Update DbConfig.js with AWS region
      replace:
        path: "{{ app_dir }}/configs/DbConfig.js"
        regexp: "<region>"
        replace: "{{ aws_region }}"

    - name: Update db.sql with database name
      replace:
        path: "{{ app_dir }}/db.sql"
        regexp: "<react_node_app>"
        replace: "{{ db_name }}"

    - name: Display db.sql content
      command: cat {{ app_dir }}/db.sql
      register: db_sql_content
      changed_when: false

    - name: Show db.sql
      debug:
        var: db_sql_content.stdout_lines

    - name: Set ownership on backend directory
      file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes
        mode: "0755"

    - name: Copy db.sql to tmp
      copy:
        src: "{{ app_dir }}/db.sql"
        dest: /tmp/db.sql
        remote_src: yes

    - name: Download MySQL repository package
      get_url:
        url: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
        dest: /tmp/mysql80-community-release-el9-1.noarch.rpm

    - name: Install MySQL repository
      yum:
        name: /tmp/mysql80-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Import MySQL GPG key
      rpm_key:
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
        state: present

    - name: Install MySQL client
      yum:
        name: mysql-community-client
        state: present

    - name: Check MySQL version
      command: mysql --version
      register: mysql_version
      changed_when: false

    - name: Display MySQL version
      debug:
        var: mysql_version.stdout

    - name: Execute SQL schema on database
      shell: |
        mysql -h "{{ db_host }}" \
              -u "{{ db_username }}" \
              -p"{{ db_password }}" < /tmp/db.sql
      no_log: true

    - name: Install NodeSource repository setup script
      shell: curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-el9.repo

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Create log directory
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"

    - name: Create .env file
      template:
        src: backend.env.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0644"

    - name: Install Node.js dependencies
      become_user: "{{ app_user }}"
      npm:
        path: "{{ app_dir }}"
        state: present

    - name: Start application with PM2
      become_user: "{{ app_user }}"
      shell: |
        cd {{ app_dir }}
        npm run serve
      environment:
        HOME: /home/{{ app_user }}

    - name: Setup PM2 startup script
      shell: |
        sudo env PATH=$PATH:/usr/bin \
        /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u {{ app_user }} \
        --hp /home/{{ app_user }} || true
      register: pm2_startup
      changed_when: "'PM2' in pm2_startup.stdout"

    - name: Save PM2 process list
      become_user: "{{ app_user }}"
      command: pm2 save
      environment:
        HOME: /home/{{ app_user }}

    - name: Install CloudWatch agent
      yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch agent configuration
      copy:
        content: |
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "{{ log_dir }}/combined.log",
                      "log_group_name": "node-app-logs-lirw-backend",
                      "log_stream_name": "{instance_id}-combined-log",
                      "timestamp_format": "%Y-%m-%d %H:%M:%S"
                    },
                    {
                      "file_path": "{{ log_dir }}/error.log",
                      "log_group_name": "node-app-logs-lirw-backend",
                      "log_stream_name": "{instance_id}-error-log",
                      "timestamp_format": "%Y-%m-%d %H:%M:%S"
                    }
                  ]
                }
              }
            }
          }
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        owner: root
        group: root
        mode: "0644"

    - name: Start CloudWatch agent
      command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config -m ec2
        -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        -s
      register: cw_agent
      changed_when: "'successfully' in cw_agent.stdout"
