---
- name: Setup and deploy Node.js backend on Amazon Linux 2023
  # hosts: appserver
  hosts: all
  become: true
  gather_facts: false
  vars:
    bucket_name: "{{ bucket_name | default(lookup('env', 'bucket_name')) }}"
    db_host: "{{ db_host | default(lookup('env', 'db_host')) }}"
    db_username: "{{ db_username | default(lookup('env', 'db_username')) }}"
    db_password: "{{ db_password | default(lookup('env', 'db_password')) }}"
    db_name: "{{ db_name | default(lookup('env', 'db_name')) }}"
    aws_region: "{{ aws_region | default(lookup('env', 'aws_region')) }}"
    ssh_username: "{{ ssh_username | default(lookup('env', 'ssh_username')) }}"
    environment_stage: "{{ environment_stage | default(lookup('env', 'environment_stage')) }}"
    repo_dir: /home/{{ ssh_username }}/backend
    log_dir: /home/{{ ssh_username }}/backend/logs
    env_file: /home/{{ ssh_username }}/backend/.env
    cloudwatch_config: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

  tasks:
    - name: Ensure log file exists
      ansible.builtin.file:
        path: /var/log/user-data.log
        state: touch
        mode: "0644"
    # this is of no use here in ansible playbook as this operation is not applicable throughout ansible
    # check /var/log/cloud-init-output.log and /var/log/cloud-init.log on the instance for user-data logs

    # - name: Redirect output to log file using tee
    #   shell: |
    #     exec > >(tee /var/log/user-data.log) 2>&1
    #     set -euo pipefail
    #   args:
    #     executable: /bin/bash
    #   ignore_errors: no # Make sure to fail the task if something goes wrong

    - name: Display bucket name
      ansible.builtin.debug:
        msg: "Bucket name is {{ bucket_name }}"

    - name: Copy backend app code from S3
      ansible.builtin.command:
        cmd: >
          aws s3 cp s3://{{ bucket_name }}/lirw-three-tier/backend {{ repo_dir }} --recursive
      args:
        creates: "{{ repo_dir }}/configs/DbConfig.js"
      become_user: "{{ ssh_username }}"

    - name: Replace region placeholder in DbConfig.js
      ansible.builtin.replace:
        path: "{{ repo_dir }}/configs/DbConfig.js"
        regexp: "<region>"
        replace: "{{ aws_region }}"

    - name: Replace environment placeholder in DbConfig.js
      ansible.builtin.replace:
        path: "{{ repo_dir }}/configs/DbConfig.js"
        regexp: "<environment>"
        replace: "{{ environment_stage }}"

    - name: Replace db name placeholder in db.sql
      ansible.builtin.replace:
        path: "{{ repo_dir }}/db.sql"
        regexp: "<react_node_app>"
        replace: "{{ db_name }}"

    - name: Ensure ownership and permissions for backend folder
      ansible.builtin.file:
        path: "{{ repo_dir }}"
        owner: "{{ ssh_username }}"
        group: "{{ ssh_username }}"
        recurse: yes
        mode: "0755"

    - name: Display db.sql content
      command: cat {{ repo_dir }}/db.sql
      register: db_sql_content
      changed_when: false

    - name: Show db.sql
      ansible.builtin.debug:
        var: db_sql_content.stdout_lines

    - name: Copy db.sql to /tmp
      ansible.builtin.copy:
        src: "{{ repo_dir }}/db.sql"
        dest: /tmp/db.sql
        remote_src: true

    # === MYSQL CLIENT INSTALLATION ===
    - name: Install MySQL community repo
      ansible.builtin.command: >
        wget https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
      args:
        chdir: /tmp
        creates: /tmp/mysql80-community-release-el9-1.noarch.rpm

    # - name: Download MySQL repository package
    #   get_url:
    #     url: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
    #     dest: /tmp/mysql80-community-release-el9-1.noarch.rpm

    # - name: Download MySQL community repo package
    #   ansible.builtin.get_url:
    #     url: "https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm"
    #     dest: "/tmp/mysql80-community-release-el9-1.noarch.rpm"
    #     mode: "0644"
    #   become: true

    - name: Install MySQL community repo RPM
      ansible.builtin.dnf:
        name: "/tmp/mysql80-community-release-el9-1.noarch.rpm"
        state: present
        disable_gpg_check: yes
        update_cache: yes
      become: true

    # - name: Install MySQL client packages
    #   ansible.builtin.dnf:
    #     name: mysql80-community-release-el9-1.noarch.rpm
    #     state: present
    #     disable_gpg_check: yes
    #   become: true
    # args:
    #   chdir: /tmp

    - name: Import MySQL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
      become: true

    - name: Install MySQL client
      ansible.builtin.dnf:
        name: mysql-community-client
        state: present
        update_cache: yes
      become: true

    - name: Check MySQL version
      ansible.builtin.command: mysql --version
      register: mysql_version
      changed_when: false

    - name: Display MySQL version
      ansible.builtin.debug:
        var: mysql_version.stdout

    # - name: Run SQL schema on remote DB
    #   ansible.builtin.command: >
    #     mysql -h {{ db_host }} -u {{ db_username }} -p{{ db_password }} < /tmp/db.sql

    - name: Execute SQL schema on database
      ansible.builtin.shell: |
        mysql -h "{{ db_host }}" \
              -u "{{ db_username }}" \
              -p"{{ db_password }}" < /tmp/db.sql
      args:
        executable: /bin/bash
      no_log: true
      ignore_errors: no

    # === SYSTEM PREP AND NODE INSTALLATION ===
    - name: Update yum packages
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes
      ignore_errors: no

    - name: Install Node.js 18.x
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        yum install -y nodejs
      args:
        executable: /bin/bash
      ignore_errors: no

    - name: Install PM2 globally
      ansible.builtin.npm:
        name: pm2
        global: true

    - name: Create log directory
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: directory
        owner: "{{ ssh_username }}"
        group: "{{ ssh_username }}"
        mode: "0755"

    # === .ENV CONFIG CREATION ===
    - name: Create environment file
      ansible.builtin.copy:
        dest: "{{ env_file }}"
        owner: "{{ ssh_username }}"
        group: "{{ ssh_username }}"
        mode: "0644"
        content: |
          LOG_DIR={{ log_dir }}
          DB_HOST={{ db_host }}
          DB_PORT=3306
          DB_USER={{ db_username }}
          DB_PASSWORD={{ db_password }}
          DB_NAME={{ db_name }}

    # === APP INSTALL & START ===
    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: "{{ repo_dir }}"
      become_user: "{{ ssh_username }}"
      ignore_errors: no

    - name: Start backend
      ansible.builtin.command: npm run serve
      args:
        chdir: "{{ repo_dir }}"
      become_user: "{{ ssh_username }}"
      ignore_errors: no

    - name: Start backend using PM2 in the background
      ansible.builtin.shell: pm2 startup || true
      args:
        chdir: "{{ repo_dir }}"
      become_user: "{{ ssh_username }}"
      ignore_errors: no

      # - name: Configure PM2 startup
      #   # ansible.builtin.shell: |
      #   #   env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u {{ ssh_username }} --hp /home/{{ ssh_username }}
      #   ignore_errors: yes

    - name: Configure PM2 startup
      ansible.builtin.shell: |
        sudo env PATH=$PATH:/usr/bin \
        /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u {{ ssh_username }} \
        --hp /home/{{ ssh_username }} || true
      become: true
      ignore_errors: no

    - name: Save PM2 process list
      ansible.builtin.command: pm2 save
      become_user: "{{ ssh_username }}"
      ignore_errors: no

    # === CLOUDWATCH AGENT SETUP ===
    - name: Install CloudWatch agent
      ansible.builtin.yum:
        name: amazon-cloudwatch-agent
        state: present
      become: true

    - name: Create CloudWatch agent configuration
      ansible.builtin.copy:
        dest: "{{ cloudwatch_config }}"
        mode: "0644"
        content: |
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "{{ log_dir }}/combined.log",
                      "log_group_name": "node-app-logs-lirw-backend",
                      "log_stream_name": "{instance_id}-combined-log",
                      "timestamp_format": "%Y-%m-%d %H:%M:%S"
                    },
                    {
                      "file_path": "{{ log_dir }}/error.log",
                      "log_group_name": "node-app-logs-lirw-backend",
                      "log_stream_name": "{instance_id}-error-log",
                      "timestamp_format": "%Y-%m-%d %H:%M:%S"
                    }
                  ]
                }
              }
            }
          }
      become: true

    - name: Start CloudWatch agent
      ansible.builtin.command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config -m ec2 -c file:{{ cloudwatch_config }} -s
      become: true
      ignore_errors: no
