---
- name: Configure Frontend Web Tier (Client)
  hosts: all
  become: yes # This will make all tasks in this play run as root
  gather_facts: false

  vars:
    bucket_name: "{{ bucket_name | default(lookup('env', 'bucket_name')) }}"
    internal_alb_dns_name: "{{ internal_alb_dns_name | default(lookup('env', 'internal_alb_dns_name')) }}"
    ssh_username: "{{ ssh_username | default(lookup('env', 'ssh_username')) }}"
    repo_dir: /home/{{ ssh_username }}/frontend
    nginx_conf: /etc/nginx/nginx.conf
    nginx_custom_conf: /etc/nginx/conf.d/presentation-tier.conf
    env_file: "{{ repo_dir }}/.env"
    app_tier_alb_url: "http://{{ internal_alb_dns_name }}"
    api_url: "/api"
    log_group_name: "nginx-logs-lirw-frontend"

  tasks:
    # this is of no use here in ansible playbook as this operation is not applicable throughout ansible
    # check /var/log/cloud-init-output.log and /var/log/cloud-init.log on the instance for user-data logs

    # - name: Ensure log file exists
    #   ansible.builtin.file:
    #     path: /var/log/user-data.log
    #     state: touch
    #     mode: "0644"

    # - name: Redirect output to log file using tee
    #   shell: |
    #     exec > >(tee /var/log/user-data.log) 2>&1
    #     set -euo pipefail
    #   ignore_errors: no # Make sure to fail the task if something goes wrong

    - name: Ensure EC2-user home exists
      ansible.builtin.file:
        path: /home/{{ ssh_username }}
        state: directory
        owner: "{{ ssh_username }}"
        group: "{{ ssh_username }}"
        mode: "0755"

    - name: Copy web-tier code from S3 bucket
      ansible.builtin.command:
        cmd: "aws s3 cp s3://{{ bucket_name }}/lirw-three-tier/frontend {{ repo_dir }} --recursive"
      args:
        creates: "{{ repo_dir }}/package.json"
      register: s3_copy_result

    - name: Set ownership and permissions on frontend directory
      ansible.builtin.file:
        path: /home/{{ ssh_username }}
        owner: "{{ ssh_username }}"
        group: "{{ ssh_username }}"
        recurse: yes
        mode: "0755"

    - name: Update system packages
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes
      become: true

    - name: Install Node.js 18.x
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        sudo yum install -y nodejs
      args:
        creates: /usr/bin/node
      become: true
      ignore_errors: no

    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present
      become: true

    - name: Enable and start NGINX
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started
      become: true
      ignore_errors: no

    # - name: Create .env file for frontend
    #   ansible.builtin.copy:
    #     dest: "{{ env_file }}"
    #     content: |
    #       VITE_API_URL="{{ api_url }}"
    #     owner: {{ ssh_username }}
    #     group: {{ ssh_username }}
    #     mode: "0644"
    - name: Create .env file for frontend
      ansible.builtin.lineinfile:
        path: "{{ env_file }}"
        line: 'VITE_API_URL="{{ api_url }}"'
        create: yes
        owner: "{{ ssh_username }}"
        group: "{{ ssh_username }}"
        mode: "0644"
      become_user: "{{ ssh_username }}"
    # - name: Install Node.js dependencies
    #   ansible.builtin.command:
    #     cmd: "npm install"
    #     chdir: "{{ repo_dir }}"
    #   become_user: {{ ssh_username }}
    - name: Install Node.js dependencies
      ansible.builtin.npm:
        path: "{{ repo_dir }}"
        state: present
      become_user: "{{ ssh_username }}"

    - name: Build frontend app
      ansible.builtin.command:
        cmd: "npm run build"
        chdir: "{{ repo_dir }}"
      become_user: "{{ ssh_username }}"

    - name: Copy built frontend to NGINX HTML directory
      ansible.builtin.copy:
        src: "{{ repo_dir }}/dist"
        dest: /usr/share/nginx/html/
        owner: nginx
        group: nginx
        mode: "0755"
        remote_src: yes

    - name: Backup existing NGINX configuration
      ansible.builtin.copy:
        src: "{{ nginx_conf }}"
        dest: "{{ nginx_conf }}.bak"
        force: no
        remote_src: yes

      become: true

    - name: Write base NGINX configuration
      ansible.builtin.copy:
        dest: "{{ nginx_conf }}"
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log warn;
          pid /run/nginx.pid;
          events {
              worker_connections 1024;
          }
          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;
              log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';
              access_log /var/log/nginx/access.log main;
              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;
              include /etc/nginx/conf.d/*.conf;
          }
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx
      become: true

    - name: Write frontend NGINX site configuration
      ansible.builtin.copy:
        dest: "{{ nginx_custom_conf }}"
        content: |
          server {
              listen 80;
              server_name _;
              root /usr/share/nginx/html/dist;
              index index.html index.htm;

              location /health {
                  default_type text/html;
                  return 200 "<!DOCTYPE html><p>Health check endpoint</p>\n";
              }

              location / {
                  try_files $uri /index.html;
              }

              location /api/ {
                  proxy_pass {{ app_tier_alb_url }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx
      become: true

    # defined under handlers below
    # - name: Restart NGINX
    #   ansible.builtin.systemd:
    #     name: nginx
    #     state: restarted

    - name: Install CloudWatch Agent
      ansible.builtin.yum:
        name: amazon-cloudwatch-agent
        state: present
      become: true

    - name: Configure CloudWatch Agent
      ansible.builtin.copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/nginx/access.log",
                      "log_group_name": "{{ log_group_name }}",
                      "log_stream_name": "{instance_id}-nginx-access",
                      "timestamp_format": "%b %d %H:%M:%S"
                    },
                    {
                      "file_path": "/var/log/nginx/error.log",
                      "log_group_name": "{{ log_group_name }}",
                      "log_stream_name": "{instance_id}-nginx-error",
                      "timestamp_format": "%b %d %H:%M:%S"
                    }
                  ]
                }
              }
            }
          }
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Start CloudWatch Agent
      ansible.builtin.command:
        cmd: >
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
          -a fetch-config -m ec2
          -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
          -s
      register: cw_agent
      changed_when: "'successfully' in cw_agent.stdout or 'Configuration validation' in cw_agent.stdout"
      become: true
      ignore_errors: no

  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      become: true
