---
- name: Setup Frontend Web Server
  hosts: all
  become: yes
  vars:
    app_user: ec2-user
    app_dir: /home/ec2-user/frontend
    nginx_html_dir: /usr/share/nginx/html
    node_version: "18.x"
    server_name: "_"
    api_url: "/api"

  tasks:
    - name: Display configuration
      debug:
        msg:
          - "Bucket: {{ bucket_name }}"
          - "Internal ALB DNS: {{ internal_alb_dns_name }}"
          - "ALB URL: http://{{ internal_alb_dns_name }}"

    - name: Change to ec2-user home directory
      file:
        path: /home/{{ app_user }}
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Copy frontend code from S3
      command: >
        aws s3 cp s3://{{ bucket_name }}/lirw-three-tier/frontend {{ app_dir }} --recursive
      args:
        creates: "{{ app_dir }}"

    - name: Set ownership on home directory
      file:
        path: /home/{{ app_user }}
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes
        mode: "0755"

    - name: Update system packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install NodeSource repository setup script
      shell: curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-el9.repo

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create .env file for frontend
      lineinfile:
        path: "{{ app_dir }}/.env"
        line: 'VITE_API_URL="{{ api_url }}"'
        create: yes
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0644"

    - name: Install Node.js dependencies
      become_user: "{{ app_user }}"
      npm:
        path: "{{ app_dir }}"
        state: present

    - name: Build frontend application
      become_user: "{{ app_user }}"
      command: npm run build
      args:
        chdir: "{{ app_dir }}"
        creates: "{{ app_dir }}/dist"
      environment:
        HOME: /home/{{ app_user }}

    - name: Copy build files to Nginx directory
      copy:
        src: "{{ app_dir }}/dist/"
        dest: "{{ nginx_html_dir }}/dist/"
        remote_src: yes
        owner: nginx
        group: nginx
        mode: "0755"

    - name: Backup existing Nginx configuration
      copy:
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf.bak
        remote_src: yes
        force: no

    - name: Create main Nginx configuration
      copy:
        content: |
          user nginx;
          worker_processes auto;

          error_log /var/log/nginx/error.log warn;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

              access_log /var/log/nginx/access.log main;

              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;

              include /etc/nginx/conf.d/*.conf;
          }
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx

    - name: Create presentation tier Nginx configuration
      template:
        src: presentation-tier.conf.j2
        dest: /etc/nginx/conf.d/presentation-tier.conf
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx

    - name: Install CloudWatch agent
      yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch agent configuration
      copy:
        content: |
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                   {
                      "file_path": "/var/log/nginx/access.log",
                      "log_group_name": "nginx-logs-lirw-frontend",
                      "log_stream_name": "{instance_id}-nginx-access",
                      "timestamp_format": "%b %d %H:%M:%S"
                    },
                    {
                      "file_path": "/var/log/nginx/error.log",
                      "log_group_name": "nginx-logs-lirw-frontend",
                      "log_stream_name": "{instance_id}-nginx-error",
                      "timestamp_format": "%b %d %H:%M:%S"
                    }
                  ]
                }
              }
            }
          }
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        owner: root
        group: root
        mode: "0644"

    - name: Start CloudWatch agent
      command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config -m ec2
        -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        -s
      register: cw_agent
      changed_when: "'successfully' in cw_agent.stdout or 'Configuration validation' in cw_agent.stdout"

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
